[platformio]
src_dir = firmware/src
include_dir = firmware/include

[env:esp32c3_4mb]
platform = espressif32@6.10.0
board = esp32-c3-devkitm-1
framework = arduino
board_upload.flash_size = 4MB
board_build.partitions = partitions/esp32c3_4mb.csv
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@7.3.1
    https://github.com/Links2004/arduinoWebSockets.git#7a4c416082b80dfc2c0da10731effc8d3a69abc6
    https://github.com/sinricpro/esp8266-esp32-sdk.git#2ad7bffd59271148503dac7f22f53b33aad499f4
build_flags = -D ARDUINO_USB_MODE=1 -D ARDUINO_USB_CDC_ON_BOOT=1
extra_scripts = pre:scripts/embed_web.py, post:scripts/size_gate.py
