#!/usr/bin/env bash
set -euo pipefail
root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
temp=$(mktemp -d); trap 'rm -rf "$temp"' EXIT
g++ -std=c++17 -Wall -Wextra -Werror -fsanitize=address,undefined -fno-omit-frame-pointer "$root/tests/test_core.cpp" -o "$temp/test_core"
"$temp/test_core"
g++ -std=c++17 -Wall -Wextra -Werror "$root/tests/test_credential_policy.cpp" -o "$temp/test_credential_policy"
"$temp/test_credential_policy"
g++ -std=c++17 -Wall -Wextra -Werror "$root/tests/test_wifi_reconnect.cpp" -o "$temp/test_wifi_reconnect"
"$temp/test_wifi_reconnect"
g++ -std=c++17 -Wall -Wextra -Werror "$root/tests/test_boot_dispatch.cpp" -o "$temp/test_boot_dispatch"
"$temp/test_boot_dispatch"
g++ -std=c++17 -Wall -Wextra -Werror -fsanitize=address,undefined "$root/tests/test_power.cpp" -o "$temp/test_power"
"$temp/test_power"
g++ -std=c++17 -Wall -Wextra -Werror "$root/tests/test_setup_network.cpp" -o "$temp/test_setup_network"
"$temp/test_setup_network"
g++ -std=c++17 -Wall -Wextra -Werror "$root/tests/test_sinric_policy.cpp" -o "$temp/test_sinric_policy"
"$temp/test_sinric_policy"
g++ -std=c++17 -Wall -Wextra -Werror "$root/tests/test_microlink_policy.cpp" -o "$temp/test_microlink_policy"
"$temp/test_microlink_policy"
g++ -std=c++17 -Wall -Wextra -Werror "$root/tests/test_microlink_runtime.cpp" -o "$temp/test_microlink_runtime"
"$temp/test_microlink_runtime"
g++ -std=c++17 -Wall -Wextra -Werror "$root/tests/test_microlink_io_policy.cpp" -o "$temp/test_microlink_io_policy"
"$temp/test_microlink_io_policy"
g++ -std=c++17 -Wall -Wextra -Werror "$root/tests/test_microlink_stream.cpp" -o "$temp/test_microlink_stream"
"$temp/test_microlink_stream"
g++ -std=c++17 -Wall -Wextra -Werror "$root/tests/test_microlink_transport_policy.cpp" -o "$temp/test_microlink_transport_policy"
"$temp/test_microlink_transport_policy"
gcc -std=c11 -Wall -Wextra -Werror -I"$root/components/microlink/src" -c "$root/components/microlink/src/ml_json_scan.c" -o "$temp/ml_json_scan.o"
g++ -std=c++17 -Wall -Wextra -Werror -I"$root/components/microlink/src" "$root/tests/test_microlink_json_scan.cpp" "$temp/ml_json_scan.o" -o "$temp/test_microlink_json_scan"
"$temp/test_microlink_json_scan"
bash "$root/tests/test_shutdown.sh"
bash "$root/tests/test_discovery.sh"
bash "$root/tests/test_efi_helpers.sh"
bash "$root/tests/test_uefi_bootnext.sh"
while IFS= read -r -d '' file; do bash -n "$file"; done < <(find "$root/agent" "$root/installer" "$root/ipxe" "$root/scripts" "$root/tests" -name '*.sh' -print0)
python3 "$root/tests/test_embed_local_wifi.py"
python3 "$root/tests/test_embed_microlink_config.py"
python3 "$root/tests/test_microlink_build_config.py"
python3 "$root/tests/test_microlink_vendor.py"
python3 "$root/tests/test_web_asset.py"
python3 "$root/tests/test_dashboard_ui.py"
node "$root/tests/test_dashboard_validation.js"
node "$root/tests/test_dashboard_polling.js"
node "$root/tests/test_microlink_dashboard.js"
python3 "$root/scripts/scan_secrets.py"
