const {test,expect}=require('@playwright/test');const {fakeApi,login,A,B}=require('./fake-api');
test('UI-01 empty registry and accessible Add PC',async({page})=>{const calls=await fakeApi(page,{empty:true});await login(page);await expect(page.getByText('Nenhum PC cadastrado.')).toBeVisible();await page.getByRole('button',{name:'Adicionar PC',exact:true}).click();await page.getByLabel('Nome do PC',{exact:true}).fill('Servidor');await page.getByLabel('MAC Ethernet',{exact:true}).fill('AA:BB:CC:DD:EE:02');await page.getByRole('button',{name:'Criar PC',exact:true}).click();await expect(page.getByLabel('PC selecionado')).toHaveValue(B);expect(calls.find(c=>c.path==='pcs'&&c.method==='POST').body.name).toBe('Servidor');});
test('UI-02/04 selection rejects late A response and captures action target',async({page})=>{const calls=await fakeApi(page,{delayed:true});await login(page);await page.getByLabel('PC selecionado').selectOption(B);await expect(page.locator('#cardOs')).toHaveText('Linux Servidor');await page.waitForTimeout(800);await expect(page.locator('#cardOs')).toHaveText('Linux Servidor');await page.locator('#overviewBoot').getByRole('button',{name:'Ligar',exact:true}).click();await expect.poll(()=>calls.some(c=>c.path===`pcs/${B}/boot`&&c.method==='POST')).toBeTruthy();expect(calls.some(c=>c.path===`pcs/${A}/boot`)).toBeFalsy();});
test('UI-03 per PC save uses explicit id and no agent credential field',async({page})=>{const calls=await fakeApi(page);await login(page);await page.getByLabel('PC selecionado').selectOption(B);await page.getByRole('button',{name:'Configuração',exact:true}).click();await page.locator('#view-settings').getByLabel('Nome do PC',{exact:true}).fill('Servidor novo');await page.getByRole('button',{name:'Salvar ajustes do PC'}).click();await expect.poll(()=>calls.some(c=>c.path===`pcs/${B}`&&c.method==='PUT'&&c.body.name==='Servidor novo')).toBeTruthy();await expect(page.locator('#f_agent_token')).toHaveCount(0);});
test('UI-05/06 pairing reviews untrusted metadata and requires confirmation',async({page})=>{const calls=await fakeApi(page);await login(page);await page.getByRole('button',{name:'Parear agent',exact:true}).click();await page.getByLabel('Código do instalador').fill('abcd-efgh');await page.getByRole('button',{name:'Consultar código'}).click();await expect(page.getByText('desktop-test • Linux')).toBeVisible();expect(calls.some(c=>c.path.endsWith('/approve'))).toBeFalsy();await page.getByLabel('PC de destino').selectOption(B);await page.getByLabel('Conferi o computador e autorizo este vínculo').check();await page.getByRole('button',{name:'Confirmar vínculo'}).click();await expect.poll(()=>calls.some(c=>c.path.endsWith('/approve')&&c.body.pc_id===B)).toBeTruthy();await expect(page.locator('#agentList').getByText(/Aguardando conexão do agent/)).toBeVisible();});
test('UI-07 cancel pairing closes window, keyboard restores focus',async({page})=>{const calls=await fakeApi(page);await login(page);await page.getByRole('button',{name:'Parear agent',exact:true}).click();await page.keyboard.press('Escape');await expect(page.locator('#pairingDialog')).not.toBeVisible();await expect.poll(()=>calls.some(c=>c.path==='pairing/window'&&c.method==='DELETE')).toBeTruthy();await expect(page.getByRole('button',{name:'Parear agent',exact:true})).toBeFocused();});
test('UI-08 Sinric PC change confirms and clears slots',async({page})=>{const calls=await fakeApi(page);await login(page);await page.getByRole('button',{name:'Sinric',exact:true}).click();page.once('dialog',dialog=>dialog.accept());await page.getByLabel('PC controlado pelo Sinric').selectOption(B);await expect(page.locator('#slots .slot-row')).toHaveCount(0);await page.getByRole('button',{name:'Salvar Sinric',exact:true}).click();await expect.poll(()=>calls.some(c=>c.path==='integrations/sinric'&&c.body.sinric_pc_id===B&&c.body.sinric_slots.length===0)).toBeTruthy();});
test('UI-09 independent tabs select independent PCs',async({page,context})=>{await fakeApi(page);await login(page);const other=await context.newPage();await fakeApi(other);await login(other);await other.getByLabel('PC selecionado').selectOption(B);await expect(page.getByLabel('PC selecionado')).toHaveValue(A);await expect(other.getByLabel('PC selecionado')).toHaveValue(B);});
test('UI-10 no horizontal overflow and dialog labels',async({page})=>{await fakeApi(page);await login(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.getByRole('button',{name:'Parear agent',exact:true}).click();await expect(page.getByRole('dialog',{name:'Parear agent'})).toBeVisible();await expect(page.getByLabel('Código do instalador')).toBeFocused();});
