const {test,expect}=require('@playwright/test');
const {fakeApi,login,A,B}=require('./fake-api');
test('expired pairing cannot be approved',async({page})=>{
 await fakeApi(page);await page.clock.install();await page.route('**/api/v2/pairing/lookup',route=>route.fulfill({json:{pairing_id:'c'.repeat(32),hostname:'test',os:'Linux',expires_in:1}}));
 await login(page);await page.getByRole('button',{name:'Parear agent',exact:true}).click();await page.getByLabel('Código do instalador').fill('ABCD-EFGH');await page.getByRole('button',{name:'Consultar código'}).click();await expect(page.locator('#pairReview')).toBeVisible();await page.getByLabel('Conferi o computador e autorizo este vínculo').check();await page.clock.fastForward(2200);await expect(page.locator('#pairError')).toContainText('Código expirado');await expect(page.getByRole('button',{name:'Confirmar vínculo'})).toBeDisabled();
});
test('persistence error keeps review open and never claims connection',async({page})=>{
 const calls=await fakeApi(page);await page.route('**/api/v2/pairing/*/approve',route=>route.fulfill({status:500,json:{error:'NVS_WRITE_FAILED'}}));await login(page);await page.getByRole('button',{name:'Parear agent',exact:true}).click();await page.getByLabel('Código do instalador').fill('ABCD-EFGH');await page.getByRole('button',{name:'Consultar código'}).click();await page.getByLabel('Conferi o computador e autorizo este vínculo').check();await page.getByRole('button',{name:'Confirmar vínculo'}).click();await expect(page.locator('#pairError')).toContainText('Nenhum vínculo foi aprovado');await expect(page.locator('#pairingDialog')).toBeVisible();await page.getByRole('button',{name:'Cancelar pareamento'}).click();await expect.poll(()=>calls.some(c=>c.method==='DELETE'&&c.path==='pairing/'+'c'.repeat(32))).toBeTruthy();
});
test('HTTP and JSON authentication errors remain visible',async({page})=>{
 await fakeApi(page);await page.route('**/api/v2/bootstrap',route=>route.fulfill({status:403,json:{error:'FORBIDDEN'}}));await login(page);await expect(page.locator('#loginError')).toContainText('Senha inválida');await page.route('**/api/v2/bootstrap',route=>route.fulfill({status:200,body:'invalid JSON'}));await page.getByRole('button',{name:'Conectar',exact:true}).click();await expect(page.locator('#loginError')).toContainText('Resposta JSON inválida');
});
test('late catalog does not overwrite an edited PC name',async({page})=>{
 await fakeApi(page);await page.route('**/api/v2/pcs/'+B+'/systems?*',async route=>{await new Promise(resolve=>setTimeout(resolve,600));await route.fulfill({json:{systems:[{id:'0001',name:'Linux'}],offset:0,generation:1,total:1}})});await login(page);await page.getByLabel('PC selecionado').selectOption(B);await page.getByRole('button',{name:'Configuração',exact:true}).click();await page.locator('#pc_name').fill('Nome editado');await page.waitForTimeout(800);await expect(page.locator('#pc_name')).toHaveValue('Nome editado');
});
test('removing Sinric PC clears selection without redirecting integration',async({page})=>{
 const calls=await fakeApi(page);await login(page);await page.getByRole('button',{name:'Configuração',exact:true}).click();page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Remover PC',exact:true}).click();await expect(page.getByLabel('PC selecionado')).toHaveValue(B);await page.getByRole('button',{name:'Sinric',exact:true}).click();await expect(page.getByLabel('PC controlado pelo Sinric')).toHaveValue('');await expect(page.locator('#slots .slot-row')).toHaveCount(0);await expect(page.locator('#f_sinric_enabled')).not.toBeChecked();expect(calls.some(c=>c.path==='pcs/'+A&&c.method==='DELETE')).toBeTruthy();
});
test('Sinric selection cancel preserves current mappings',async({page})=>{
 await fakeApi(page);await login(page);await page.getByRole('button',{name:'Sinric',exact:true}).click();page.once('dialog',dialog=>dialog.dismiss());await page.getByLabel('PC controlado pelo Sinric').selectOption(B);await expect(page.getByLabel('PC controlado pelo Sinric')).toHaveValue(A);await expect(page.locator('#slots .slot-row')).toHaveCount(1);
});
test('catalog generation changes restart pagination without mixing entries',async({page})=>{
 await fakeApi(page);let changed=false;await page.route('**/api/v2/pcs/'+B+'/systems?*',route=>{const offset=Number(new URL(route.request().url()).searchParams.get('offset'));if(offset===8)changed=true;const generation=changed?2:1;const systems=Array.from({length:offset===0?8:1},(_,index)=>({id:String(offset+index).padStart(4,'0'),name:(generation===2?'Atual ':'Antigo ')+(offset+index)}));return route.fulfill({json:{systems,offset,generation,total:9}})});await login(page);await page.getByLabel('PC selecionado').selectOption(B);await page.getByRole('button',{name:'Boot',exact:true}).click();await expect(page.locator('#buttons .boot-card')).toHaveCount(9);await expect(page.locator('#buttons .boot-card').first()).toContainText('Atual 0');await expect(page.locator('#buttons')).not.toContainText('Antigo');
});
