#pragma once

#if SOC_CPU_CORES_NUM == 1
#define ML_TASK_NET_IO_CORE tskNO_AFFINITY
#define ML_TASK_DERP_TX_CORE tskNO_AFFINITY
#define ML_TASK_COORD_CORE tskNO_AFFINITY
#define ML_TASK_WG_MGR_CORE tskNO_AFFINITY
#else
#define ML_TASK_NET_IO_CORE 0
#define ML_TASK_DERP_TX_CORE 0
#define ML_TASK_COORD_CORE 1
#define ML_TASK_WG_MGR_CORE 1
#endif

#define ML_NOISE_FRAME_BUFFER_SIZE (24 * 1024)
